import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { BsFillMoonStarsFill } from "react-icons/bs"
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai"
import { useState } from "react"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
   
        <div className={darkMode ? "dark" : ""} >
            <Head>
                <title>Rohit's Portofolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between">
                        <h1 className="text-xl text-teal-600">Portofolio</h1>
                        <ul className="flex item-center">
                            <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl text-teal-600" /></li>

                        </ul>
                    </nav>
                    <div className="text-center p-10">
                        <h1 className="text-5xl text-teal-600 font-medium md:text-6xl">Rohit Ojha</h1>
                        <h2 className="text-2xl p-10 bg:text-white-800 text-teal-600">Software Developer</h2>
                        <p className="text-md text-2xl py-5 leading-8 text-gray-800">
                            Freelancer providing software and desinging contant and need to join me below and lets get cracking
                        </p>
                    </div>

                    <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
                        <AiFillGithub />
                        <AiFillLinkedin />
                    </div>

                </section>
            </main>
        </div>
  )
}
